added new C programs
swastikians/CACS151 pull request #5
Opened 2023-03-29 13:55 UTC by theanjali01

2023-03-30 02:55 UTC, sgrdev commented on 01_arg_and_return.exe
please gitignore executables

2023-03-30 02:56 UTC, sgrdev commented on pattern/05_zeroandone
this file is missing .c extension

2023-03-30 02:56 UTC, sgrdev requested changes
please fix the issues i mentioned

2023-03-31 13:47 UTC, skdhg requested changes

2023-03-31 13:47 UTC, skdhg commented on 01_arg_and_return.exe
@theanjali01 pls remove this file 😓

2023-03-31 13:47 UTC, skdhg commented on controlStatement/05_switch-case.c
why is it commented?

2023-03-31 14:46 UTC, skdhg approved these changes

2023-03-31 14:47 UTC, merged